import React from 'react'
import {createRoot} from 'react-dom/client'
import './styles.css'
const API=import.meta.env.VITE_API_URL||'http://localhost:3000/api/v1'
const el=(t:any,p:any,...c:any[])=>React.createElement(t,p,...c)
const empty={firstName:'',middleName:'',lastName:'',citizenship:'',birthDate:'',phone:'',email:''}
function App(){
 const [token,setToken]=React.useState(localStorage.getItem('token')); const [email,setEmail]=React.useState('admin@example.local'); const [password,setPassword]=React.useState('ChangeMe-123!')
 const [active,setActive]=React.useState('Главная'); const [q,setQ]=React.useState(''); const [error,setError]=React.useState('')
 const [foreigners,setForeigners]=React.useState<any[]>([]); const [selected,setSelected]=React.useState<any>(null); const [show,setShow]=React.useState(false); const [form,setForm]=React.useState(empty); const [doc,setDoc]=React.useState({documentType:'Паспорт',documentNumber:'',issuingCountry:'',issueDate:'',expiryDate:''}); const [visa,setVisa]=React.useState({visaType:'Рабочая',visaNumber:'',issueDate:'',startDate:'',endDate:'',notes:''})
 const [data,setData]=React.useState<any>({}); const [saving,setSaving]=React.useState(false)
 async function api(path:string,opts:any={}){
  const r=await fetch(API+path,{...opts,headers:{'Content-Type':'application/json',Authorization:'Bearer '+token,...(opts.headers||{})}}); const d=await r.json().catch(()=>({})); if(!r.ok)throw new Error(d.message||'Ошибка запроса'); return d
 }
 async function login(e:any){e.preventDefault();setError('');try{const d=await api('/auth/login',{method:'POST',headers:{Authorization:''},body:JSON.stringify({email,password})});localStorage.setItem('token',d.accessToken);setToken(d.accessToken)}catch(e:any){setError(e.message)}}
 async function loadForeigners(){try{const d=await api('/foreigners?q='+encodeURIComponent(q));setForeigners(d.data||[])}catch(e:any){setError(e.message)}}
 async function loadSection(){
  setError(''); try{
   if(active==='Главная')setData(await api('/dashboard'))
   if(active==='Контроль сроков')setData(await api('/deadlines'))
   if(active==='Документы'){const [d,v]=await Promise.all([api('/documents'),api('/visas')]);setData({documents:d.data||[],visas:v.data||[]})}
   if(active==='История')setData(await api('/history'))
   if(active==='Е-паслуга')setData(await api('/applications'))
   if(active==='Отчёты')setData(await api('/dashboard'))
  }catch(e:any){setError(e.message)}
 }
 React.useEffect(()=>{if(token)loadForeigners()},[token,q])
 React.useEffect(()=>{if(token)loadSection()},[token,active])
 function field(n:string,v:string){setForm((x:any)=>({...x,[n]:v}))}
 async function saveForeigner(e:any){e.preventDefault();setSaving(true);try{await api('/foreigners',{method:'POST',body:JSON.stringify(form)});setShow(false);setForm(empty);await loadForeigners()}catch(e:any){setError(e.message)}finally{setSaving(false)}}
 async function openForeigner(x:any){try{setSelected(await api('/foreigners/'+x.id))}catch(e:any){setError(e.message)}}
 async function saveDoc(e:any){e.preventDefault();try{await api('/documents',{method:'POST',body:JSON.stringify({...doc,foreignerId:selected.foreigner.id})});setDoc({documentType:'Паспорт',documentNumber:'',issuingCountry:'',issueDate:'',expiryDate:''});await openForeigner(selected.foreigner)}catch(e:any){setError(e.message)}}
 async function saveVisa(e:any){e.preventDefault();try{await api('/visas',{method:'POST',body:JSON.stringify({...visa,foreignerId:selected.foreigner.id})});setVisa({visaType:'Рабочая',visaNumber:'',issueDate:'',startDate:'',endDate:'',notes:''});await openForeigner(selected.foreigner)}catch(e:any){setError(e.message)}}
 async function archive(id:string){if(!confirm('Архивировать запись?'))return;try{await api('/foreigners/'+id,{method:'DELETE'});setSelected(null);await loadForeigners()}catch(e:any){setError(e.message)}}
 if(!token)return el('div',{className:'login'},el('form',{onSubmit:login},el('h1',null,'ForeignID'),el('p',null,'Система учета иностранных граждан'),el('input',{value:email,onChange:(e:any)=>setEmail(e.target.value),placeholder:'Email'}),el('input',{type:'password',value:password,onChange:(e:any)=>setPassword(e.target.value),placeholder:'Пароль'}),error&&el('div',{className:'error'},error),el('button',{className:'primary'},'Войти'),el('small',null,'Демо: admin@example.local / ChangeMe-123!')))
 const nav=['Главная','Иностранцы','Контроль сроков','Е-паслуга','Документы','Отчёты','История','Настройки']
 const card=(n:any,l:string)=>el('div',{className:'stat'},el('b',null,String(n??0)),el('span',null,l))
 function dashboard(){return el('div',null,el('h1',null,'Главная'),el('p',{className:'muted'},'Единая рабочая панель ForeignID'),el('div',{className:'cards'},card(data.foreigners,'Иностранцев'),card(data.documents,'Документов'),card(data.visas,'Активных виз'),card(data.registrations,'Регистраций'),card(data.todayActions,'Операций сегодня')),el('div',{className:'panel pad'},el('h2',null,'Что контролируется'),el('p',null,'Паспорта и другие документы, визы и разрешения, регистрации и история изменений.')))
 function foreignersPage(){return el('div',null,el('div',{className:'page-title-row'},el('div',null,el('h1',null,'Иностранцы'),el('p',{className:'muted'},'Полная карточка, документы, визы и сроки')),el('button',{className:'primary',onClick:()=>setShow(true)},'+ Добавить иностранца')),error&&el('div',{className:'error'},error),el('div',{className:'panel'},el('table',null,el('thead',null,el('tr',null,...['ФИО','Гражданство','Документ','Виза до','Регистрация до','Действия'].map(x=>el('th',null,x)))),el('tbody',null,...foreigners.filter(x=>x.status!=='ARCHIVED').map(x=>el('tr',{key:x.id},el('td',null,el('button',{className:'link',onClick:()=>openForeigner(x)},x.last_name+' '+x.first_name+' '+(x.middle_name||''))),el('td',null,x.citizenship),el('td',null,x.document?.document_number||'—'),el('td',null,x.visa?.end_date||'—'),el('td',null,x.registration?.end_date||'—'),el('td',null,el('button',{onClick:()=>openForeigner(x)},'Открыть'))))))),
 show&&el('div',{className:'modal-backdrop'},el('div',{className:'modal'},el('div',{className:'modal-header'},el('h2',null,'Добавить иностранца'),el('button',{onClick:()=>setShow(false)},'×')),el('form',{onSubmit:saveForeigner},el('div',{className:'form-grid'},...[
  ['Имя *','firstName'],['Фамилия *','lastName'],['Отчество','middleName'],['Гражданство *','citizenship'],['Дата рождения','birthDate'],['Телефон','phone'],['Email','email']].map(([l,n]:any)=>el('label',null,l,el('input',{type:n==='birthDate'?'date':n==='email'?'email':'text',required:l.includes('*'),value:(form as any)[n],onChange:(e:any)=>field(n,e.target.value)}))),),el('div',{className:'modal-actions'},el('button',{type:'button',onClick:()=>setShow(false)},'Отмена'),el('button',{className:'primary',disabled:saving},saving?'Сохранение...':'Сохранить')))))
 }
 function detail(){if(!selected)return null;const f=selected.foreigner;return el('div',{className:'detail'},el('button',{className:'back',onClick:()=>setSelected(null)},'← К списку'),el('div',{className:'page-title-row'},el('div',null,el('h1',null,f.last_name+' '+f.first_name+' '+(f.middle_name||'')),el('p',{className:'muted'},f.citizenship+' · '+(f.birth_date||'дата рождения не указана'))),el('button',{className:'danger',onClick:()=>archive(f.id)},'Архивировать')),el('div',{className:'grid2'},el('div',{className:'panel pad'},el('h2',null,'Персональные данные'),el('p',null,'Телефон: ',f.phone||'—'),el('p',null,'Email: ',f.email||'—')),el('div',{className:'panel pad'},el('h2',null,'Документы'),...selected.documents.map((d:any)=>el('div',{className:'record'},el('b',null,d.document_type+' №'+d.document_number),el('span',null,'До '+d.expiry_date)))),el('div',{className:'panel pad'},el('h2',null,'Добавить / заменить документ'),el('form',{onSubmit:saveDoc,className:'stack'},el('input',{placeholder:'Тип документа',value:doc.documentType,onChange:(e:any)=>setDoc({...doc,documentType:e.target.value})}),el('input',{placeholder:'Номер',required:true,value:doc.documentNumber,onChange:(e:any)=>setDoc({...doc,documentNumber:e.target.value})}),el('input',{placeholder:'Страна выдачи',value:doc.issuingCountry,onChange:(e:any)=>setDoc({...doc,issuingCountry:e.target.value})}),el('label',null,'Дата выдачи',el('input',{type:'date',value:doc.issueDate,onChange:(e:any)=>setDoc({...doc,issueDate:e.target.value})})),el('label',null,'Срок действия',el('input',{type:'date',required:true,value:doc.expiryDate,onChange:(e:any)=>setDoc({...doc,expiryDate:e.target.value})})),el('button',{className:'primary'},'Сохранить документ'))),el('div',{className:'panel pad'},el('h2',null,'Визы и разрешения'),...selected.visas.map((v:any)=>el('div',{className:'record'},el('b',null,v.visa_type+(v.visa_number?' №'+v.visa_number:'')),el('span',null,'Действует до '+v.end_date))),el('form',{onSubmit:saveVisa,className:'stack'},el('h3',null,'Добавить визу / разрешение'),el('input',{placeholder:'Тип визы',required:true,value:visa.visaType,onChange:(e:any)=>setVisa({...visa,visaType:e.target.value})}),el('input',{placeholder:'Номер',value:visa.visaNumber,onChange:(e:any)=>setVisa({...visa,visaNumber:e.target.value})}),el('label',null,'Начало',el('input',{type:'date',value:visa.startDate,onChange:(e:any)=>setVisa({...visa,startDate:e.target.value})})),el('label',null,'Окончание *',el('input',{type:'date',required:true,value:visa.endDate,onChange:(e:any)=>setVisa({...visa,endDate:e.target.value})})),el('textarea',{placeholder:'Примечание',value:visa.notes,onChange:(e:any)=>setVisa({...visa,notes:e.target.value})}),el('button',{className:'primary'},'Сохранить визу'))))}
 function section(){if(active==='Главная')return dashboard();if(active==='Иностранцы')return foreignersPage();if(active==='Настройки')return el('div',{className:'panel pad'},el('h1',null,'Настройки'),el('p',null,'Роль: ORG_ADMIN'),el('p',{className:'muted'},'Управление доступом и параметры организации.'));if(active==='Контроль сроков')return el('div',null,el('h1',null,'Контроль сроков'),el('p',{className:'muted'},'Документы, визы и регистрации с ближайшими сроками.'),el('div',{className:'panel'},el('table',null,el('thead',null,el('tr',null,...['ФИО','Тип','Запись','Дата окончания','Статус'].map(x=>el('th',null,x)))),el('tbody',null,...(data.data||[]).map((x:any)=>el('tr',null,el('td',null,x.last_name+' '+x.first_name),el('td',null,x.item_type),el('td',null,x.item_name),el('td',null,x.end_date),el('td',null,el('span',{className:x.deadline_status==='EXPIRED'?'bad':'warn'},x.deadline_status==='EXPIRED'?'ПРОСРОЧЕНО':'СКОРО'))))))));if(active==='Документы')return el('div',null,el('h1',null,'Документы'),el('p',{className:'muted'},'Реестр документов и виз.'),el('div',{className:'grid2'},el('div',{className:'panel pad'},el('h2',null,'Документы'),...(data.documents||[]).map((d:any)=>el('div',{className:'record'},el('b',null,d.last_name+' '+d.first_name),el('span',null,d.document_type+' №'+d.document_number+' · до '+d.expiry_date)))),el('div',{className:'panel pad'},el('h2',null,'Визы'),...(data.visas||[]).map((v:any)=>el('div',{className:'record'},el('b',null,v.last_name+' '+v.first_name),el('span',null,v.visa_type+' · до '+v.end_date)))));if(active==='История')return el('div',null,el('h1',null,'История'),el('p',{className:'muted'},'Последние 100 операций.'),el('div',{className:'panel'},(data.data||[]).map((x:any)=>el('div',{className:'history'},el('b',null,x.action+' · '+x.entity_type),el('span',null,new Date(x.created_at).toLocaleString()+' · '+(x.first_name||'система')))));if(active==='Е-паслуга')return el('div',null,el('h1',null,'Е-паслуга'),el('p',{className:'muted'},'Заявки, подготовленные для передачи через официальный государственный сервис.'),el('div',{className:'panel'},(data.data||[]).length?(data.data||[]).map((x:any)=>el('div',{className:'history'},el('b',null,x.service_type),el('span',null,(x.last_name||'')+' '+(x.first_name||'')+' · '+x.status))):el('div',{className:'pad'},'Заявок пока нет. Создание заявки будет доступно из карточки иностранца.')));if(active==='Отчёты')return el('div',{className:'panel pad'},el('h1',null,'Отчёты'),el('p',null,'Сводка по организации'),el('ul',null,el('li',null,'Иностранцев: ',data.foreigners),el('li',null,'Документов: ',data.documents),el('li',null,'Активных виз: ',data.visas),el('li',null,'Регистраций: ',data.registrations)));return null}
 return el('div',{className:'app'},el('aside',null,el('h2',null,'◈ ForeignID'),...nav.map(x=>el('button',{className:'nav '+(active===x?'active':''),onClick:()=>{setActive(x);setSelected(null)},key:x},x)),el('button',{className:'logout',onClick:()=>{localStorage.removeItem('token');setToken(null)}},'Выйти')),el('main',null,el('header',null,el('input',{placeholder:'Поиск по ФИО, гражданству...',value:q,onChange:(e:any)=>setQ(e.target.value)}),el('span',null,'Иванов А.А.')),selected?detail():section()))
}
createRoot(document.getElementById('root')!).render(el(App,null))